"""Synthetic data helpers for the physics review of cq_tdm (read-only on the repo)."""
import numpy as np
from cq_tdm.core.dicom_loader import DicomImage, DicomSeries


def white_noise(rng, shape, sigma):
    return rng.normal(0.0, sigma, size=shape)


def ct_like_spectrum(fr, f0):
    """Radial 2D NPS model of FBP: S(f) ∝ f·exp(-(f/f0)^2) (ramp x gaussian apodisation)."""
    return fr * np.exp(-(fr / f0) ** 2)


def ct_like_noise(rng, shape, pixel_mm, sigma, f0):
    """Correlated noise whose 2D NPS is S(f) = C·f·exp(-(f/f0)^2), total variance sigma^2.

    Generated by spectral shaping of white noise on the full image grid.
    """
    rows, cols = shape
    fy = np.fft.fftfreq(rows, d=pixel_mm)
    fx = np.fft.fftfreq(cols, d=pixel_mm)
    FX, FY = np.meshgrid(fx, fy)
    fr = np.hypot(FX, FY)
    S = ct_like_spectrum(fr, f0)
    w = rng.normal(0.0, 1.0, size=shape)
    W = np.fft.fft2(w)
    H = np.sqrt(S)
    out = np.real(np.fft.ifft2(W * H))
    out *= sigma / out.std()
    return out


def analytic_fmean_ct_like(f0):
    """Mean frequency of S(f)=f·exp(-(f/f0)^2) on [0, inf): (sqrt(pi)/2)·f0."""
    return np.sqrt(np.pi) / 2.0 * f0


def fmean_numeric(f, s, fmax=None):
    """Trapezoid mean frequency of a 1D spectrum, optionally truncated at fmax."""
    f = np.asarray(f); s = np.asarray(s)
    if fmax is not None:
        m = f <= fmax + 1e-12
        f, s = f[m], s[m]
    num = np.trapezoid(f * s, f)
    den = np.trapezoid(s, f)
    return num / den if den > 0 else 0.0


def make_image(noise, pixel_mm=0.5, matrix=512, radius_px=200.0, center=None,
               wall_hu=120.0, wall_px=8, air_hu=-1000.0, water_mean=0.0, cupping=0.0):
    """Water disc (noise + mean + optional parabolic cupping) in a PMMA-like wall, air outside."""
    rows = cols = matrix
    if center is None:
        center = (rows / 2.0, cols / 2.0)
    y, x = np.ogrid[:rows, :cols]
    dist = np.hypot(y - center[0], x - center[1])
    img = np.full((rows, cols), air_hu, dtype=float)
    img[dist <= radius_px + wall_px] = wall_hu
    water = dist <= radius_px
    field = water_mean + cupping * (dist / radius_px) ** 2 + noise
    img[water] = field[water]
    return DicomImage(pixel_array=img, rows=rows, columns=cols,
                      pixel_spacing=(pixel_mm, pixel_mm),
                      reconstruction_diameter=rows * pixel_mm,
                      slice_location=0.0)


def make_series(n, noise_fn, pixel_mm=0.5, matrix=512, seed=0, **kw):
    rng = np.random.default_rng(seed)
    images = []
    for i in range(n):
        noise = noise_fn(rng, (matrix, matrix))
        im = make_image(noise, pixel_mm=pixel_mm, matrix=matrix, **kw)
        im.slice_location = float(i)
        im.instance_number = i + 1
        images.append(im)
    return DicomSeries(images=images)
